---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wave-server.fullname" . }}
  labels:
    {{- include "wave-server.labels" . | nindent 4 }}
data:
  index.html: |
    <html>
    <h1>{{ .Values.server.title }}</h1>
    {{ .Values.server.message }}
    </html>
